# D has units of nm
d_min: 150
d_max: 825
d_step: 75

# Ms has units of kA/m
ms_min: 260
ms_max: 460
ms_step: 20

# Ku is specified as int, in the end it will be divided by 100 with units MJ/m3
ku_min: 2
ku_max: 22
ku_step: 2

# DMI is specified as int, will be divided by 10 with units of J/m2
dmi_min: 10
dmi_max: 25
dmi_step: 5

# T has units of K
temperature: 0

# Absolute path to prepend
abs_path: !ENV ${ABS_PATH}

